add react project
Code-Your-Future/refugee-match pull request #1
Opened 2017-03-19 16:00 UTC by Ehmed-kino

is there any comments you need to add for this pull request ?

2017-03-19 16:11 UTC, TheoLeanse commented
@Ehmed-kino doesn't look like this will be using node

2017-03-19 16:28 UTC, Md-Almasri requested changes
delete unnecessary files

2017-03-20 09:44 UTC, ahmed-kino reviewed
@Md-Almasri  I deleted extra things from react folder and added really basic logo as well

2017-03-20 10:09 UTC, Md-Almasri commented on public/index.html
> +    <title>React App</title>
@Ehmed-kino could you please change the title?

2017-03-20 10:11 UTC, Md-Almasri approved these changes
Nice, could you merge your changes please?

2017-03-20 13:38 UTC, merged